### PR TITLE
Updated polymorphic bench and added new images

### LINKED ISSUE #9: polymorphic vs monomorphic
Jakob Kummerow [wrote](http://disq.us/p/1kvomfk):

> I can't reproduce (or explain) your results for "polymorphic functions" with a plain d8 binary. While it always has been and always will be true that polymorphism has a speed cost, it doesn't make sense that a single "obj.length" load amid all the other stuff (creating objects, branching, calling, looping) would cause a 2x slowdown *overall*, because all the other code (like the empty loop) is not affected by that one polymorphic property load.

How can we update the benchmark in a way that is meaningful? cc @bmeurer @fhinkel @hashseed @TimothyGu

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #9.

### CODE REVIEW

**Comment by davidmarkclements** [comment]
so this changes the actual benchmark

instead of testing polymorphic *types* we're testing polymorphic *object shapes*

isn't that fundamentally different?

What we first described is an API that supports, say, string and object input 

(e.g. like [`upring.add`](https://www.npmjs.com/package/upring#add) 
can take objects or strings) 

This is different, far more subtle - since its testing different object compositions (what keys and value types do they have)

What I'm saying is, I don't think one should replace the other

**Comment by davidmarkclements** [comment]
@mcollina I've added polymorphic types to the benchmark 

since we're dealing with types and we ultimately need numbers, the types test 
has to do coercion, to cancel out the cost of coercion we now do coercion
in the other benchmarks 

results seem to show that polymorphic types are more costly that polymorphic object shapes 

```js
polymorphic x 14,655 ops/sec ±2.34% (85 runs sampled)
polymorphic (types) x 7,731 ops/sec ±1.50% (89 runs sampled)
monomorphic x 19,797 ops/sec ±0.98% (88 runs sampled)
Fastest is monomorphic
```

@jakobkummerow @hashseed @bmeurer - does this check out?

Once we've confirmed the benchmarks fidelity I'll update the content to reflect the findings

**Comment by davidmarkclements** [comment]
damn. 

nope it still doesn't work

if I explicitly change type in polymorphic types (e.g. change
`sum += typeof o === 'object' ? o.a : o` to `sum += typeof o === 'object' ? o.a : +o`)
 the polymorphic types benchmark jumps to being slightly faster than monomorphic 
(probably confounded by the attempt to isolate coercion, and maybe less object creation?)

I'd really like to measure actual type inputs to prove (or not) that they're the same cost as changing object shapes

@jakobkummerow @hashseed @bmeurer @fhinkel Any suggestions?

**Comment by jakobkummerow** [comment]
> instead of testing polymorphic types we're testing polymorphic object shapes
> isn't that fundamentally different?

Object shapes *are* types.

The snippet I've provided demonstrates the effect of a polymorphic property load. That's the typical case of polymorphism in JavaScript.

Arguably binary operations can also be called "polymorphic" when e.g. an addition operates on a mix of strings/numbers/objects. That's a separate case though (different use case for developers, different implementation in V8, different where-is-the-time-spent profile), and I don't see the point of throwing it in with the polymorphic property access.

With the `sum += typeof o === 'object' ? o.a : +o` line you've changed the benchmark to have a very different focus. You're free to do that of course, but then don't call it "polymorphism" please.

**Comment by davidmarkclements** [comment]
Ok interesting 

So l, coming from a JS dev perspective, what I'm interested in is two things 

1. What effect does having a function accept a string, or object, or null, or number (primitives vs objects) vs just accepting objects
2. The object shape "types" case (again for a JS dev I wouldn't call these types, since typeof an object will always object) 

To be clear are we saying that a string vs an object and an object vs a different shaped object is the same thing (because whilst a string is a primitive it's also an object)? How does this figure with `null` or `undefined` inputs? 

How can I demonstrate that the string vs object  and the object1 vs object2 are the the same (or different)? 

My goal here is to translate these results into something that's demonstrable and easy to explain from the JS perspective for JS devs

**Comment by jakobkummerow** [comment]
It's not about *functions accepting things*. For example, `function identity(x) { return x; }` will have exactly the same speed regardless of what you throw at it. Conversely, any kind of polymorphism you can create with a function, you can also create without any function calls being involved.

*Individual operations* care about types, because they have to adapt their behavior. The prime example is property loads and stores. Those care a lot about different object shapes. That's polymorphism, and I think it's really important to explain *that* kind of polymorphism to JS devs, precisely because due to how the language works they might find it surprising that this concept even exists. I already gave you an example for how to demonstrate the speed difference.

Mixing primitives and objects only rarely makes sense, because there are so few operations that (reasonably) apply to both of them. (Of course you *can* load properties from numbers and they'll be looked up on the `Number` prototype, but in my experience when a program does that it's usually a bug.) The most frequent example is probably string concatenation (think `console.log("the index is " + i + " and the value is " + array[i]);`), but that's mostly dominated by to-string conversion rather than polymorphism of the addition.

If you insist on toying with a polymorphic addition, take a `function add(a, b) { return a+b; }` and see what happens when you call it with:
- only integers
- only doubles
- only strings
- only objects `{valueOf: function() { return 42; }}`
- various combinations of the above

(Or, to tie this back to the first paragraph, just perform an addition without doing a function call; the polymorphism is the same...)
Just be careful not to attribute to polymorphism what's actually caused by conversions. And watch out for constant folding and dead code elimination. Or just avoid drawing conclusions from microbenchmarks... ;-)

**Comment by mcollina** [comment]
@jakobkummerow thanks for explaining! I've reverted the changes @davidmarkclements has made. I will integrate your explanation with the text.

**Comment by mcollina** [comment]
@jakobkummerow I've updated the explanation, would you mind double checking?

**Comment by jakobkummerow** [comment]
Yes, sounds better now. You still have a headline suggesting that polymorphism is something that applies to functions though.

**Comment by mcollina** [comment]
Thanks @jakobkummerow!

**Pull request merged**
